import { db } from "./db";
import { dealers, cars } from "@shared/schema";
import { count } from "drizzle-orm";
import { log } from "./index";

export async function seedDatabase() {
  const [existing] = await db.select({ count: count() }).from(dealers);
  if (Number(existing.count) > 0) {
    log("Database already seeded, skipping", "seed");
    return;
  }

  log("Seeding database with initial data...", "seed");

  const dealerData = [
    {
      name: "Toshkent Avto",
      slug: "toshkent-avto",
      description: "Official Chevrolet dealer in Tashkent with over 15 years of experience. We offer new and certified pre-owned vehicles with full warranty and after-sales support.",
      phone: "+998 71 200 10 10",
      address: "Mustaqillik ko'chasi 42",
      city: "Tashkent",
      region: "Toshkent shahri",
      verified: true,
      rating: "4.8",
      totalSales: 1240,
    },
    {
      name: "Samarqand Motors",
      slug: "samarqand-motors",
      description: "Largest multi-brand dealership in the Samarkand region. Specializing in Korean and Japanese imports with competitive pricing.",
      phone: "+998 66 233 45 67",
      address: "Registon ko'chasi 15",
      city: "Samarkand",
      region: "Samarqand",
      verified: true,
      rating: "4.6",
      totalSales: 850,
    },
    {
      name: "Farg'ona AutoPlus",
      slug: "fargona-autoplus",
      description: "Family-owned dealership serving the Fergana Valley. Known for honest pricing and excellent customer service.",
      phone: "+998 73 244 56 78",
      address: "Al-Farg'oniy ko'chasi 8",
      city: "Fergana",
      region: "Farg'ona",
      verified: true,
      rating: "4.5",
      totalSales: 620,
    },
    {
      name: "Buxoro Avto Savdo",
      slug: "buxoro-avto-savdo",
      description: "Premium dealership in historic Bukhara. Authorized service center for Chevrolet and Kia vehicles.",
      phone: "+998 65 221 34 56",
      address: "Navoiy ko'chasi 22",
      city: "Bukhara",
      region: "Buxoro",
      verified: true,
      rating: "4.4",
      totalSales: 430,
    },
    {
      name: "Andijon Cars",
      slug: "andijon-cars",
      description: "Trusted car dealership in Andijan offering a wide range of vehicles. Flexible financing options available.",
      phone: "+998 74 226 78 90",
      address: "Bobur ko'chasi 5",
      city: "Andijan",
      region: "Andijon",
      verified: false,
      rating: "4.2",
      totalSales: 310,
    },
  ];

  const insertedDealers = await db.insert(dealers).values(dealerData).returning();

  const carData = [
    {
      dealerId: insertedDealers[0].id,
      make: "Chevrolet",
      model: "Malibu 2",
      year: 2024,
      price: 32500,
      mileage: 1200,
      fuelType: "petrol" as const,
      transmission: "automatic" as const,
      bodyType: "sedan" as const,
      color: "White",
      engineSize: "1.5",
      description: "Brand new Chevrolet Malibu 2 with full equipment package. Includes leather seats, panoramic sunroof, and advanced safety features. Factory warranty included.",
      imageUrl: "/images/car-1.png",
      status: "available" as const,
      featured: true,
      city: "Tashkent",
      region: "Toshkent shahri",
    },
    {
      dealerId: insertedDealers[0].id,
      make: "Chevrolet",
      model: "Tracker",
      year: 2024,
      price: 28000,
      mileage: 3500,
      fuelType: "petrol" as const,
      transmission: "automatic" as const,
      bodyType: "suv" as const,
      color: "Black",
      engineSize: "1.2",
      description: "Stylish and practical Chevrolet Tracker. Turbocharged engine, spacious interior, and modern infotainment system. Perfect for city and highway driving.",
      imageUrl: "/images/car-2.png",
      status: "available" as const,
      featured: true,
      city: "Tashkent",
      region: "Toshkent shahri",
    },
    {
      dealerId: insertedDealers[1].id,
      make: "Chevrolet",
      model: "Cobalt",
      year: 2023,
      price: 15500,
      mileage: 18000,
      fuelType: "gas" as const,
      transmission: "manual" as const,
      bodyType: "sedan" as const,
      color: "Silver",
      engineSize: "1.5",
      description: "Reliable Chevrolet Cobalt with LPG system installed. Excellent fuel economy and low maintenance costs. One owner, full service history.",
      imageUrl: "/images/car-3.png",
      status: "available" as const,
      featured: true,
      city: "Samarkand",
      region: "Samarqand",
    },
    {
      dealerId: insertedDealers[1].id,
      make: "Chevrolet",
      model: "Onix",
      year: 2023,
      price: 18000,
      mileage: 12000,
      fuelType: "petrol" as const,
      transmission: "automatic" as const,
      bodyType: "sedan" as const,
      color: "Red",
      engineSize: "1.0",
      description: "Compact and efficient Chevrolet Onix with turbocharged engine. Modern design with excellent safety ratings. Low mileage, like new condition.",
      imageUrl: "/images/car-4.png",
      status: "available" as const,
      featured: true,
      city: "Samarkand",
      region: "Samarqand",
    },
    {
      dealerId: insertedDealers[2].id,
      make: "Kia",
      model: "K5",
      year: 2024,
      price: 35000,
      mileage: 5000,
      fuelType: "petrol" as const,
      transmission: "automatic" as const,
      bodyType: "sedan" as const,
      color: "White",
      engineSize: "2.0",
      description: "Premium Kia K5 with GT-Line package. Features include ventilated seats, heads-up display, and Bose sound system. Imported directly from Korea.",
      imageUrl: "/images/car-5.png",
      status: "available" as const,
      featured: true,
      city: "Fergana",
      region: "Farg'ona",
    },
    {
      dealerId: insertedDealers[3].id,
      make: "Hyundai",
      model: "Tucson",
      year: 2023,
      price: 38000,
      mileage: 8000,
      fuelType: "diesel" as const,
      transmission: "automatic" as const,
      bodyType: "suv" as const,
      color: "Dark Blue",
      engineSize: "2.0",
      description: "Powerful Hyundai Tucson diesel with all-wheel drive. Perfect for Uzbekistan's diverse terrain. Full service history, one owner.",
      imageUrl: "/images/car-6.png",
      status: "available" as const,
      featured: true,
      city: "Bukhara",
      region: "Buxoro",
    },
    {
      dealerId: insertedDealers[0].id,
      make: "Chevrolet",
      model: "Equinox",
      year: 2024,
      price: 42000,
      mileage: 2000,
      fuelType: "petrol" as const,
      transmission: "automatic" as const,
      bodyType: "suv" as const,
      color: "Gray",
      engineSize: "1.5",
      description: "All-new Chevrolet Equinox with turbo engine. Spacious 5-seater SUV with premium interior. Advanced driver assistance features included.",
      imageUrl: "/images/car-2.png",
      status: "available" as const,
      featured: false,
      city: "Tashkent",
      region: "Toshkent shahri",
    },
    {
      dealerId: insertedDealers[2].id,
      make: "BYD",
      model: "Song Plus",
      year: 2024,
      price: 29000,
      mileage: 500,
      fuelType: "hybrid" as const,
      transmission: "automatic" as const,
      bodyType: "suv" as const,
      color: "White",
      engineSize: "1.5",
      description: "BYD Song Plus DM-i plug-in hybrid. Exceptional fuel economy with electric-only range of 110km. Modern Chinese engineering at its best.",
      imageUrl: "/images/car-5.png",
      status: "available" as const,
      featured: false,
      city: "Fergana",
      region: "Farg'ona",
    },
    {
      dealerId: insertedDealers[3].id,
      make: "Toyota",
      model: "Camry",
      year: 2022,
      price: 35000,
      mileage: 25000,
      fuelType: "petrol" as const,
      transmission: "automatic" as const,
      bodyType: "sedan" as const,
      color: "Black",
      engineSize: "2.5",
      description: "Toyota Camry - the gold standard of reliability. Well-maintained with full service records. Imported from UAE with low mileage.",
      imageUrl: "/images/car-1.png",
      status: "available" as const,
      featured: false,
      city: "Bukhara",
      region: "Buxoro",
    },
    {
      dealerId: insertedDealers[4].id,
      make: "Lada",
      model: "Vesta",
      year: 2023,
      price: 12000,
      mileage: 15000,
      fuelType: "gas" as const,
      transmission: "manual" as const,
      bodyType: "sedan" as const,
      color: "Silver",
      engineSize: "1.6",
      description: "Affordable and practical Lada Vesta with factory-installed LPG system. Great value for money with modern features and comfortable ride.",
      imageUrl: "/images/car-3.png",
      status: "available" as const,
      featured: false,
      city: "Andijan",
      region: "Andijon",
    },
    {
      dealerId: insertedDealers[0].id,
      make: "Geely",
      model: "Coolray",
      year: 2024,
      price: 24000,
      mileage: 3000,
      fuelType: "petrol" as const,
      transmission: "automatic" as const,
      bodyType: "suv" as const,
      color: "Blue",
      engineSize: "1.5",
      description: "Sporty Geely Coolray crossover with turbocharged engine. Packed with technology including 360-degree camera and adaptive cruise control.",
      imageUrl: "/images/car-6.png",
      status: "available" as const,
      featured: false,
      city: "Tashkent",
      region: "Toshkent shahri",
    },
    {
      dealerId: insertedDealers[1].id,
      make: "Chery",
      model: "Tiggo 7 Pro",
      year: 2024,
      price: 26000,
      mileage: 1000,
      fuelType: "petrol" as const,
      transmission: "automatic" as const,
      bodyType: "suv" as const,
      color: "White",
      engineSize: "1.5",
      description: "Feature-rich Chery Tiggo 7 Pro. Premium interior quality with large touchscreen. Excellent value in the compact SUV segment.",
      imageUrl: "/images/car-5.png",
      status: "available" as const,
      featured: false,
      city: "Samarkand",
      region: "Samarqand",
    },
  ];

  await db.insert(cars).values(carData);
  log(`Seeded ${dealerData.length} dealers and ${carData.length} cars`, "seed");
}
